apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.HelloWorldJob.AppName }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox-printer
            image: busybox:latest
            args:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
    