apiVersion: batch/v1
kind: CronJob
metdata:
  name: {{ .Values.HelloWorldJob.AppName }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
    template:
      spec:
        containers:
        - name: {{ .Values.HelloWorldJob.AppName }}
          image: busybox:latest
          args:
          - /bin/sh
          - -c
          - date
        restartPolicy: OnFailure
    