apiVersion: apps/v1
kind: Deployment
metadata:
  name: testchart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testchart
  template:
    metadata:
      labels:
        app: testchart
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
